import type { Shop, Product } from '@/types/product';

export const mockShops: Shop[] = [
  {
    id: 'shop-1',
    ownerId: 'user-2',
    name: 'VibeTech Official',
    ratingVibe: 4.8,
  },
  {
    id: 'shop-2',
    ownerId: 'user-2',
    name: 'Fashion Hub',
    ratingVibe: 4.5,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    shopId: 'shop-1',
    name: 'Tai nghe Bluetooth VibeBuds Pro chống ồn chủ động ANC',
    isApproved: true,
    deletedAt: null,
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60',
    soldCount: 1520,
    variants: [
      {
        id: 'var-1-1',
        productId: 'prod-1',
        price: 890000,
        stock: 50,
        attributes: { color: 'Black' },
      },
      {
        id: 'var-1-2',
        productId: 'prod-1',
        price: 950000,
        stock: 30,
        attributes: { color: 'White' },
      },
    ],
  },
  {
    id: 'prod-2',
    shopId: 'shop-1',
    name: 'Bàn phím cơ VibeKey K68 Switch Red Hotswap',
    isApproved: true,
    deletedAt: null,
    thumbnail: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=500&auto=format&fit=crop&q=60',
    soldCount: 840,
    variants: [
      {
        id: 'var-2-1',
        productId: 'prod-2',
        price: 1250000,
        stock: 15,
        attributes: { color: 'Black', switch: 'Red' },
      },
    ],
  },
  {
    id: 'prod-3',
    shopId: 'shop-2',
    name: 'Áo thun nam Cotton form rộng phong cách Basic',
    isApproved: true,
    deletedAt: null,
    thumbnail: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&auto=format&fit=crop&q=60',
    soldCount: 3200,
    variants: [
      {
        id: 'var-3-1',
        productId: 'prod-3',
        price: 150000,
        stock: 100,
        attributes: { color: 'White', size: 'M' },
      },
      {
        id: 'var-3-2',
        productId: 'prod-3',
        price: 150000,
        stock: 100,
        attributes: { color: 'White', size: 'L' },
      },
      {
        id: 'var-3-3',
        productId: 'prod-3',
        price: 150000,
        stock: 80,
        attributes: { color: 'Black', size: 'M' },
      },
      {
        id: 'var-3-4',
        productId: 'prod-3',
        price: 150000,
        stock: 80,
        attributes: { color: 'Black', size: 'L' },
      },
    ],
  },
  {
    id: 'prod-4',
    shopId: 'shop-2',
    name: 'Quần jean nam ống suông dáng Hàn Quốc',
    isApproved: true,
    deletedAt: null,
    thumbnail: 'https://images.unsplash.com/photo-1542272604-780c4050d153?w=500&auto=format&fit=crop&q=60',
    soldCount: 950,
    variants: [
      {
        id: 'var-4-1',
        productId: 'prod-4',
        price: 280000,
        stock: 45,
        attributes: { color: 'Blue', size: '30' },
      },
      {
        id: 'var-4-2',
        productId: 'prod-4',
        price: 280000,
        stock: 50,
        attributes: { color: 'Blue', size: '31' },
      },
      {
        id: 'var-4-3',
        productId: 'prod-4',
        price: 280000,
        stock: 60,
        attributes: { color: 'Blue', size: '32' },
      },
    ],
  },
  {
    id: 'prod-5',
    shopId: 'shop-1',
    name: 'Chuột không dây VibeMouse M1 Silent Ergonomic',
    isApproved: true,
    deletedAt: null,
    thumbnail: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format&fit=crop&q=60',
    soldCount: 2100,
    variants: [
      {
        id: 'var-5-1',
        productId: 'prod-5',
        price: 350000,
        stock: 120,
        attributes: { color: 'Gray' },
      },
      {
        id: 'var-5-2',
        productId: 'prod-5',
        price: 350000,
        stock: 85,
        attributes: { color: 'Pink' },
      },
    ],
  },
  {
    id: 'prod-6',
    shopId: 'shop-2',
    name: 'Giày sneaker nam nữ dáng thể thao năng động',
    isApproved: true,
    deletedAt: null,
    thumbnail: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&auto=format&fit=crop&q=60',
    soldCount: 4500,
    variants: [
      {
        id: 'var-6-1',
        productId: 'prod-6',
        price: 450000,
        stock: 30,
        attributes: { color: 'White', size: '39' },
      },
      {
        id: 'var-6-2',
        productId: 'prod-6',
        price: 450000,
        stock: 40,
        attributes: { color: 'White', size: '40' },
      },
      {
        id: 'var-6-3',
        productId: 'prod-6',
        price: 450000,
        stock: 45,
        attributes: { color: 'White', size: '41' },
      },
      {
        id: 'var-6-4',
        productId: 'prod-6',
        price: 450000,
        stock: 50,
        attributes: { color: 'White', size: '42' },
      },
    ],
  },
  {
    id: 'prod-7',
    shopId: 'shop-1',
    name: 'Đồng hồ thông minh VibeWatch Pro màn hình AMOLED',
    isApproved: true,
    deletedAt: null,
    thumbnail: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500&auto=format&fit=crop&q=60',
    soldCount: 680,
    variants: [
      {
        id: 'var-7-1',
        productId: 'prod-7',
        price: 1850000,
        stock: 25,
        attributes: { color: 'Silver' },
      },
      {
        id: 'var-7-2',
        productId: 'prod-7',
        price: 1850000,
        stock: 20,
        attributes: { color: 'Black' },
      },
    ],
  },
  {
    id: 'prod-8',
    shopId: 'shop-2',
    name: 'Balo laptop nam nữ chống nước cao cấp',
    isApproved: true,
    deletedAt: null,
    thumbnail: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop&q=60',
    soldCount: 1250,
    variants: [
      {
        id: 'var-8-1',
        productId: 'prod-8',
        price: 320000,
        stock: 60,
        attributes: { color: 'Black' },
      },
      {
        id: 'var-8-2',
        productId: 'prod-8',
        price: 320000,
        stock: 40,
        attributes: { color: 'Navy' },
      },
    ],
  },
];
